language: generic
sudo: required
services:
    - docker

before-install:
    - docker build -t vishalkini/my-repo -f Dockerfile.dev .

script:    
    - docker run -e CI=true vishalkini/my-repo npm run test    
    

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"   
    app: "docker-react" 
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-206597227938"
    bucket_path: "docker-react" 
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY    
